repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: nix develop --command alejandra --check
        language: system
        files: \.nix$

      - id: statix
        name: statix
        entry: nix develop --command statix check .
        language: system
        pass_filenames: false
        files: \.nix$

      - id: deadnix
        name: deadnix
        entry: nix develop --command deadnix .
        language: system
        pass_filenames: false
        files: \.nix$