# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usbhid"
      "usb_storage"
      "sr_mod"
      "sd_mod"
    ];

    initrd.kernelModules = [];

    kernelModules = [
      "kvm-intel"
      "v4l2loopback"
      "snd-aloop"
    ];

    extraModulePackages = [config.boot.kernelPackages.v4l2loopback];
  };

  # noatime is access time NOT change time (ctime) or modification time (mtime)

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8017dc36-9408-4a47-9de5-6d048cd080e2";
    fsType = "btrfs";
    options = ["subvol=@root" "compress=zstd:1" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/8017dc36-9408-4a47-9de5-6d048cd080e2";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd:1" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8017dc36-9408-4a47-9de5-6d048cd080e2";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd:1" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EED6-CA1F";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  /*
  swapDevices = [
    {device = "/dev/disk/by-uuid/be10efe9-8020-45f9-aa1c-3fdbe59a56e0";}
  ];
  */
  swapDevices = lib.mkForce []; # This system has a HDD WHY did I have a swap device lol

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f0u4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
