name: Autoformat (alejandra)

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Format Nix files
        run: nix run nixpkgs#alejandra -- .

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(fmt): run alejandra"
