name: Flake check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Set up Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            max-jobs = 1
            cores = 2

      - name: Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run flake check
        run: nix flake check path:. --all-systems --accept-flake-config --max-jobs 1