name: Flake health checker

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**/*.nix"
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at 00:00
  workflow_dispatch: # Allows manual triggering from GitHub UI

permissions:
  pull-requests: write # Allows writing comments on PRs

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Check flake.lock health
        uses: DeterminateSystems/flake-checker-action@main
        with:
          flake-lock-path: flake.lock
          fail-mode: true
          send-statistics: true # Sends an automated status comment on Pull Requests.
