name: Flake checker

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1" # weekly on Monday
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Check flake.lock health
        uses: DeterminateSystems/flake-checker-action@main
        with:
          flake-lock-path: flake.lock
          fail-mode: true
