name: "Build & cache"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-lyra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Set up Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            max-jobs = 1
            cores = 2

      - name: Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: 'skifli-nixos'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build nixOS system (lyra)
        run: |
          nix build .?submodules=1#nixosConfigurations.lyra.config.system.build.toplevel \
            --accept-flake-config \
            --max-jobs 1