name: "Nix maid"

on:
  push:
    branches:
      - main
    paths:
      - "**/*.nix"
  pull_request:
    paths:
      - "**/*.nix"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  nix-maid:
    name: Auto-fix, format, and PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix & Enable Cache
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Auto-remove - Deadnix
        run: nix run nixpkgs#deadnix -- --edit --exclude "users/programs/browser/zen/profile-default/hidden" -- .

      - name: Auto-fix - Statix
        run: nix run nixpkgs#statix -- fix --ignore "users/programs/browser/zen/profile-default/hidden" .

      - name: Auto-format - nixfmt
        run: |
          find . -name "*.nix" ! -path "*/users/programs/browser/zen/profile-default/hidden/*" -exec nix run nixpkgs#nixfmt-rfc-style -- {} +

      - name: Create PR with all the fixes
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(nix): nixfmt + deadnix + statix"
          title: "chore(nix): automated nix cleanup"
          body: |
            This is an automated PR generated by GitHub Actions.

            **Tools run:**
            * Nixfmt.
            * Deadnix.
            * Statix.
          branch: "automation/nix-cleanup"
          reviewers: skifli
          assignees: skifli
          labels: cleanup, automated
          delete-branch: true
