name: "Flake.lock: update Nix dependencies"

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at 00:00
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  update-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Configure global Git auth
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        env:
          NIX_CONFIG: "access-tokens = github.com=${{ secrets.GH_PAT }}"
        with:
          token: ${{ secrets.GH_PAT }}
          pr-title: "Bump flake.lock"
          pr-assignees: "skifli"
          pr-labels: |
            dependencies
            automated
          commit-msg: "chore(flake.lock): update"
