name: "Flake.lock: update Nix dependencies"

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday at 00:00
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  update-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(flake.lock): update"
          pr-assignees: "skifli"
          pr-labels: |
            dependencies
            automated
          commit-msg: "chore(flake.lock): update"